FelczynskiDebski.MovieApp.UI/Controllers/FilmStudiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FelczynskiDebski.MovieApp.BL;
using FelczynskiDebski.MovieApp.BL.Models;
using FelczynskiDebski.MovieApp.CORE;
using FelczynskiDebski.MovieApp.CORE.Models;
using FelczynskiDebski.MovieApp.DAO.Models;
using FelczynskiDebski.MovieApp.INTERFACES;
using FelczynskiDebski.MovieApp.UI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FelczynskiDebski.MovieApp.UI.Controllers
{
    public class FilmStudiosController : Controller
    {
        private readonly IFilmStudioDao _filmStudioDao;
        private readonly IMovieDao _movieDao;
        private readonly FilmStudioService _filmStudioService;

        public FilmStudiosController(
            IFilmStudioDao filmStudioDao,
            IMovieDao movieDao,
            FilmStudioService filmStudioService
        )
        {
            _filmStudioDao = filmStudioDao;
            _movieDao = movieDao;
            _filmStudioService = filmStudioService;
        }

        [HttpPost]
        public IActionResult SetDataSource(string dataSource)
        {
            // Store the selected data source in the session
            HttpContext.Session.SetString("DataSource", dataSource);

            // Redirect the user back to the main page
            return RedirectToAction("Index");
        }

        public IActionResult Index(string searchString, FilmStudioCountry? selectedCountry)
        {
            return View(_filmStudioService.Index(searchString, selectedCountry));
        }

        private IActionResult GetFilmStudioView(int? id)
        {
            var filmStudio = _filmStudioService.GetFilmStudioView(id);
            if (filmStudio == null)
            {
                return NotFound();
            }

            return View(filmStudio);
        }

        private IActionResult GetFilmStudioView(int? id, string viewName)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmStudioDto = _filmStudioService.GetFilmStudioViewTwo(id);
            if (filmStudioDto == null)
            {
                return NotFound();
            }

            return View(viewName, filmStudioDto);
        }

        // GET: FilmStudios/Details/5
        public IActionResult Details(int? id)
        {
            return GetFilmStudioView(id, "Details");
        }

        // GET: FilmStudios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FilmStudios/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,Country")] FilmStudio filmStudio)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var existingFilmStudio = _filmStudioDao
                        .GetAll()
                        .FirstOrDefault(fs => fs.Name == filmStudio.Name);
                    if (existingFilmStudio != null)
                    {
                        ModelState.AddModelError(
                            "",
                            "A film studio with the same name already exists."
                        );
                        return View(filmStudio);
                    }

                    _filmStudioDao.Add(filmStudio);
                    return RedirectToAction(nameof(Index));
                }
                catch (ArgumentException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(filmStudio);
        }

        // GET: FilmStudios/Edit/5
        public IActionResult Edit(int? id)
        {
            return GetFilmStudioView(id);
        }

        // POST: FilmStudios/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Country")] FilmStudio filmStudio)
        {
            // Fetch the old FilmStudio from the _filmStudioDao
            var oldFilmStudio = _filmStudioDao.Get(filmStudio.Id);
            if (oldFilmStudio == null)
            {
                return NotFound();
            }

            // Update the properties of the old FilmStudio
            oldFilmStudio.Name = filmStudio.Name;
            oldFilmStudio.Country = filmStudio.Country;

            // Fetch the movies that have the same FilmStudioId as the old film studio
            var movies = _movieDao.GetAll().Where(m => m.FilmStudioId == oldFilmStudio.Id).ToList();

            // If there are movies that have the same FilmStudioId as the old film studio, update the Movies list of the old FilmStudio
            if (movies.Any())
            {
                oldFilmStudio.Movies = movies;
            }
            else
            {
                // If there are no such movies, preserve the Movies list of the old FilmStudio
                var updatedFilmStudio = _filmStudioDao.Get(oldFilmStudio.Id);
                if (updatedFilmStudio != null)
                {
                    oldFilmStudio.Movies = updatedFilmStudio.Movies.ToList();
                }
            }

            _filmStudioDao.Update(oldFilmStudio);

            return RedirectToAction(nameof(Index));
        }

        // GET: FilmStudios/Delete/5
        public IActionResult Delete(int? id)
        {
            return GetFilmStudioView(id, "Delete");
        }

        // POST: FilmStudios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _filmStudioService.DeletePost(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

FelczynskiDebski.MovieApp.UI/Views/FilmStudios/Create.cshtml
@model FelczynskiDebski.MovieApp.BL.Models.FilmStudioDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FilmStudio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                @Html.DropDownListFor(model => model.Country,
                    Enum.GetValues(typeof(FelczynskiDebski.MovieApp.CORE.Models.FilmStudioCountry))
                        .Cast<FelczynskiDebski.MovieApp.CORE.Models.FilmStudioCountry>()
                        .Select(e => new SelectListItem { Text = e.ToString(), Value = ((int)e).ToString() }),
                    "Select Country",
                    new { @class = "form-control" })
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@* @section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
} *@

FelczynskiDebski.MovieApp.UI/Views/FilmStudios/Delete.cshtml
@model FelczynskiDebski.MovieApp.BL.Models.FilmStudioDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FilmStudio</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd>
            @Model.Country.ToString().PascalCaseToSentence()
        </dd>

    </dl>
    <h3>Movies:</h3>
    <ul>
        @if (Model.Movies != null)
        {
            foreach (var movie in Model.Movies)
            {
                <li>@movie.Title</li>
            }
        }
    </ul>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FelczynskiDebski.MovieApp.UI/Views/FilmStudios/Details.cshtml
@model FelczynskiDebski.MovieApp.BL.Models.FilmStudioDto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FilmStudio</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd>
            @Model.Country.ToString().PascalCaseToSentence()
        </dd>
    </dl>
</div>

<h3>Movies:</h3>
<ul>
    @if (Model.Movies != null)
    {
        foreach (var movie in Model.Movies)
        {
            <li>@movie.Title</li>
        }
    }
</ul>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FelczynskiDebski.MovieApp.UI/Views/FilmStudios/Edit.cshtml
@using FelczynskiDebski.MovieApp.CORE.Models
@model FelczynskiDebski.MovieApp.BL.Models.FilmStudioDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FilmStudio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                @Model.Country.ToString().PascalCaseToSentence()
                <select asp-for="Country" class="form-control"
                        asp-items="Html.GetEnumSelectList<FilmStudioCountry>()"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<h3>Movies:</h3>
<ul>
    @if (Model.Movies != null)
    {
        foreach (var movie in Model.Movies)
        {
            <li>@movie.Title</li>
        }
    }
</ul>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FelczynskiDebski.MovieApp.UI/Views/FilmStudios/Index.cshtml
@model FelczynskiDebski.MovieApp.BL.Models.FilmStudioCountryDtoViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="FilmStudios" asp-action="Index" method="get">
    <p>
        Country: <select asp-for="SelectedCountry" asp-items="Model.Countries">
            <option value="">All</option>
        </select>
        Film Studio Name: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <caption>List of Film Studios</caption>
    <thead>
        @{
            var firstFilmStudio = Model.FilmStudios?.FirstOrDefault();
        }
        @if (firstFilmStudio != null)
        {
            <tr>
                <th>
                    @Html.DisplayNameFor(model => firstFilmStudio.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => firstFilmStudio.Country)
                </th>
                <th>Movies</th>
                <th></th>
            </tr>
        }
    </thead>
    <tbody>
        @if (Model.FilmStudios != null)
        {
            @foreach (var item in Model.FilmStudios)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @item.Country.ToString().PascalCaseToSentence()
                    </td>
                    <td>
                        <ul>
                            @if (item.Movies != null && item.Movies.Any())
                            {
                                foreach (var movie in item.Movies)
                                {
                                    <li>@movie.Title</li>
                                }
                            }
                            else
                            {
                                <li>No movies</li>
                            }
                        </ul>
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }   }
    </tbody>
</table>